version: '3'
services:
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/sapi
    ports:
      - "3000:3000"
    env_file:
      - '.env'
    depends_on:
      - db
      - redis

  db:
    image: postgres
    ports:
      - "5432:5432"
    env_file:
      - '.env'
 
  redis:
    image: redis

  sidekiq:
     build: .
     volumes:
       - .:/sapi
     links:
       - db
       - redis
     command: bundle exec sidekiq -C config/sidekiq.yml
     env_file:
       - '.env'
